name: Publish Python Package

on:
  push:
    tags:
      - "v*"  # triggers on any tag like v0.1.0
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/matlabpy
    permissions:
      id-token: write  # for OIDC publishing to PyPI

    steps:
      # Step 1: Checkout the repo
      - uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # Step 3: Install Poetry
      - name: Install Poetry
        run: pipx install poetry

      # Step 4: Build the package
      - name: Build Python package
        run: poetry build

      # Step 3: Publish to PyPI
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
